language: node_js
node_js:
  - "7"
  - "6"
sudo: required
services:
  - docker

before_install:
  - docker pull jboss/keycloak
  - docker run -p 8080:8080 -e KEYCLOAK_USER=test -e KEYCLOAK_PASSWORD=test jboss/keycloak
